apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kubeseal.sandbox1.dplatk8s.iagcloud.net
  labels:
    argocd.argoproj.io/instance: kubeseal-webgui
    enable-external-dns: enable
  name: kubeseal-webgui-dns-cname
  namespace: kubeseal-webgui
spec:
  externalName: app.sandbox1.dplatk8s.iagcloud.net
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
